FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y full-upgrade \
    && apt-get install -y ubuntu-minimal ubuntu-standard ubuntu-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash attacker \
    && passwd -l attacker

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
